apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: nodejs
    spec:
      containers:
        - env:
            - name: DB_URL
              value: mongodb://db:27017/Passwords
            - name: PORT
              value: "8081"
            - name: PRODUCTION
              value: "false"
          image: smartsnake/nodejs
          name: nodejs
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /home/node/app
              name: nodejs-claim0
            - mountPath: /home/node/app/node_modules
              name: node-modules
      restartPolicy: Always
      volumes:
        - name: nodejs-claim0
          persistentVolumeClaim:
            claimName: nodejs-claim0
        - name: node-modules
          persistentVolumeClaim:
            claimName: node-modules
status: {}
